const WELCOME="WELCOME"
const LOGIN="LOGIN"
const SIGNUP="SIGNUP"
const DASHBOARD="Chats"
const SPLASH="SPLASH"
const SETTING="Setting"
const BOTTOMTAB="BOTTOMTAB"
const PROFILE="PROFILE"
const DASHBOARDSCREEN="Dashboard"
const SETTINGSCREEN="Setting"
const SHOWFULLIMG="SHOWFULLIMG"
const CHAT="CHAT"


export {
    WELCOME,
    LOGIN,
    SIGNUP,
    DASHBOARD,
    SPLASH,
    SETTING,
    BOTTOMTAB,
    PROFILE,
    DASHBOARDSCREEN,
    SETTINGSCREEN,
    SHOWFULLIMG,
    CHAT
};