const WELCOME="WELCOME"
const LOGIN="LOGIN"
const SIGNUP="SIGNUP"
const DASHBOARD="DASHBOARD"
const SPLASH="SPLASH"
const SETTING="Setting"
const BOTTOMTAB="BOTTOMTAB"
const PROFILE="PROFILE"

export {
    WELCOME,
    LOGIN,
    SIGNUP,
    DASHBOARD,
    SPLASH,
    SETTING,
    BOTTOMTAB,
    PROFILE
};